lints.workspace           = true
package.edition.workspace = true
package.name              = "expr-parser"

[dev-dependencies]
expect-test.workspace = true

[dependencies]
memchr = { version = "2.8.0" }
